# Site settings
title: Robert
email: rob.v.rodriguez@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A simple, whitespace, helvetica based portfolio theme.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username: rob_rodz1
github_username:  robrodz

# Build settings
markdown: kramdown
gems: [jekyll-paginate]
highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


